name: CI
on:
  push:
  #pull_request:
jobs:
  simple-vuex-store:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.n*
          ./*/node_modules
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18.3.0
    - run: npm -v ; node -v
    - run: npm --prefix simple-vuex-store i -E
    - run: npm --prefix simple-vuex-store run build
  json-server-fake-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.n*
          ./*/node_modules
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18.3.0
    - run: npm -v ; node -v
    - run: npm --prefix json-server-fake-api i -E
    - run: npm --prefix json-server-fake-api run build
  # vuetify-axios-vuex-nuxt-manual:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/cache@v2
  #     id: cache
  #     with:
  #       path: |
  #         ~/.n*
  #         ./*/node_modules
  #         ~/.m2/repository
  #         !~/.m2/repository/com/gituhb/daggerok
  #       key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: 18.3.0
  #   - run: npm -v ; node -v
  #   - run: npm --prefix vuetify-axios-vuex-nuxt-manual i -E
  #   - run: npm --prefix vuetify-axios-vuex-nuxt-manual run build
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.n*
          ./*/node_modules
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18.3.0
    - run: npm -v ; node -v
    - run: npm --prefix json-server-fake-api i -E
    - run: npm --prefix json-server-fake-api run gh
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: json-server-fake-api/dist # The folder the action should deploy.
